name: Build LaTeX document and release
on: 
  push:
    tags:
      - "v*.*.*"
    branches: 
      - "main"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Mitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: mitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Foerdermitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: foerdermitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Publish mitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: mitgliedsantrag.pdf
          path: mitgliedsantrag.pdf
          retention-days: 7
      - name: Publish foerdermitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: foerdermitgliedsantrag.pdf
          path: foerdermitgliedsantrag.pdf
          retention-days: 7
      - name: Get current date 
        id: date 
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Release 
        uses: softprops/action-gh-release@v3
        with:
          name: "${{env.DATE}}"
          files: | 
            foerdermitgliedsantrag.pdf
            mitgliedsantrag.pdf
