name: Build LaTeX document and release
on: 
  pull_request:
    types: 
      - closed
    branches: 
      - master
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build_latex:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Mitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: mitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Foerdermitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: foerdermitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Publish mitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: mitgliedsantrag.pdf
          path: mitgliedsantrag.pdf
          retention-days: 7
      - name: Publish foerdermitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: foerdermitgliedsantrag.pdf
          path: foerdermitgliedsantrag.pdf
          retention-days: 7
      - name: Create release tag
        uses: igorgatis/date-time-commit-release@v2
        with:
          commit: main
          tag.format: "v{YYYY}-{MM}-{DD}-{sha:5}"
      - name: Release 
        uses: softprops/action-gh-release@v3
        with:
          files: | 
            foerdermitgliedsantrag.pdf
            mitgliedsantrag.pdf
