name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Mitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: mitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Foerdermitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: foerdermitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Publish mitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: mitgliedsantrag.pdf
          path: mitgliedsantrag.pdf
      - name: Publish foerdermitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: foerdermitgliedsantrag.pdf
          path: foerdermitgliedsantrag.pdf
