name: Build LaTeX document and release
on: 
  pull_request:
    types: 
      - closed
    branches: 
      - master
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build_latex:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Mitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: mitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Foerdermitgliedsantrag
        uses: dante-ev/latex-action@latest
        with:
          root_file: foerdermitgliedsantrag.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Publish mitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: mitgliedsantrag.pdf
          path: mitgliedsantrag.pdf
          retention-days: 7
      - name: Publish foerdermitgliedsantrag
        uses: actions/upload-artifact@v4
        with:
          name: foerdermitgliedsantrag.pdf
          path: foerdermitgliedsantrag.pdf
          retention-days: 7
      - name: Get current date 
        id: date 
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Get commit stub 
        id: stub 
        run: echo "STUB=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Push tag 
        id: tag_version 
        uses: mathieudutour/github-tag-action@v6.2
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
          custom_tag: "${{env.DATE}}-${{env.STUB}}"
      - name: Release 
        uses: softprops/action-gh-release@v3
        with:
          files: | 
            foerdermitgliedsantrag.pdf
            mitgliedsantrag.pdf
          tag_name: ${{steps.tag_version.outputs.new_tag}}
          body: ${{steps.tag_version.outputs.changelog}}
